### ISSUE TITLE
Association is ignored when target Class is set to ignore -> true

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-EA-to-RDF#7]
When a class is set to ignore = true, all associations with that class as a target are also ignored.

**Expected behavior:**

Class A -> association -> Class B
Class B: ignore = true
The association is still listed as a property with domain:Class A

**Comment by DieterDePaepe** [comment]
This is the intended behavior: ignoring an element makes it invisible to the converter. Since connectors need a source and target, connectors for which their source or target are ignored, are also ignored.

Expected behavior can be achieved by instead of ignoring the class, setting its `uri` to `http://www.w3.org/2000/01/rdf-schema#Resource`.

The tooling currently doesn't support creation of properties without domain/range.
